import type { CountryPreset, RestaurantLocalizationConfig } from '../types/restaurantConfig';

/**
 * Standard international presets for the platform.
 * Covers 20 key restaurant markets across all major economic regions.
 *
 * Each preset provides turnkey localization: currency, tax regime, timezone,
 * phone format, dietary labeling system, and default payment provider.
 */
export const RESTAURANT_PRESETS: Record<string, CountryPreset> = {
  // ─── Asia-Pacific ──────────────────────────────────
  IN: {
    country: 'IN',
    name: 'India',
    currency: 'INR',
    currencySymbol: '₹',
    locale: 'en-IN',
    timezone: 'Asia/Kolkata',
    phoneCountryCode: '+91',
    taxLabel: 'GST',
    taxRate: 0.05,
    taxMode: 'inclusive',
    dietarySystem: 'india',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'razorpay',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Barrackpore',
      region: 'West Bengal',
      postalCode: '700120',
    },
  },
  AU: {
    country: 'AU',
    name: 'Australia',
    currency: 'AUD',
    currencySymbol: 'A$',
    locale: 'en-AU',
    timezone: 'Australia/Sydney',
    phoneCountryCode: '+61',
    taxLabel: 'GST',
    taxRate: 0.10,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Sydney',
      region: 'NSW',
      postalCode: '2000',
    },
  },
  NZ: {
    country: 'NZ',
    name: 'New Zealand',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    locale: 'en-NZ',
    timezone: 'Pacific/Auckland',
    phoneCountryCode: '+64',
    taxLabel: 'GST',
    taxRate: 0.15,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Auckland',
      region: 'Auckland',
      postalCode: '1010',
    },
  },
  SG: {
    country: 'SG',
    name: 'Singapore',
    currency: 'SGD',
    currencySymbol: 'S$',
    locale: 'en-SG',
    timezone: 'Asia/Singapore',
    phoneCountryCode: '+65',
    taxLabel: 'GST',
    taxRate: 0.09,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Singapore',
      region: 'Central',
      postalCode: '018956',
    },
  },
  JP: {
    country: 'JP',
    name: 'Japan',
    currency: 'JPY',
    currencySymbol: '¥',
    locale: 'ja-JP',
    timezone: 'Asia/Tokyo',
    phoneCountryCode: '+81',
    taxLabel: '消費税',
    taxRate: 0.10,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Tokyo',
      region: 'Tokyo',
      postalCode: '100-0001',
    },
  },
  TH: {
    country: 'TH',
    name: 'Thailand',
    currency: 'THB',
    currencySymbol: '฿',
    locale: 'th-TH',
    timezone: 'Asia/Bangkok',
    phoneCountryCode: '+66',
    taxLabel: 'VAT',
    taxRate: 0.07,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Bangkok',
      region: 'Bangkok',
      postalCode: '10110',
    },
  },

  // ─── North America ─────────────────────────────────
  US: {
    country: 'US',
    name: 'United States',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    timezone: 'America/New_York',
    phoneCountryCode: '+1',
    taxLabel: 'Sales Tax',
    taxRate: 0.0825,
    taxMode: 'exclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'New York',
      region: 'NY',
      postalCode: '10001',
    },
  },
  CA: {
    country: 'CA',
    name: 'Canada',
    currency: 'CAD',
    currencySymbol: 'CA$',
    locale: 'en-CA',
    timezone: 'America/Toronto',
    phoneCountryCode: '+1',
    taxLabel: 'HST',
    taxRate: 0.13,
    taxMode: 'exclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Toronto',
      region: 'Ontario',
      postalCode: 'M5V 2T6',
    },
  },
  MX: {
    country: 'MX',
    name: 'Mexico',
    currency: 'MXN',
    currencySymbol: 'MX$',
    locale: 'es-MX',
    timezone: 'America/Mexico_City',
    phoneCountryCode: '+52',
    taxLabel: 'IVA',
    taxRate: 0.16,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Ciudad de México',
      region: 'CDMX',
      postalCode: '06600',
    },
  },

  // ─── Europe ────────────────────────────────────────
  GB: {
    country: 'GB',
    name: 'United Kingdom',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    timezone: 'Europe/London',
    phoneCountryCode: '+44',
    taxLabel: 'VAT',
    taxRate: 0.20,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'London',
      region: 'Greater London',
      postalCode: 'EC1A 1BB',
    },
  },
  DE: {
    country: 'DE',
    name: 'Germany',
    currency: 'EUR',
    currencySymbol: '€',
    locale: 'de-DE',
    timezone: 'Europe/Berlin',
    phoneCountryCode: '+49',
    taxLabel: 'MwSt.',
    taxRate: 0.19,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Berlin',
      region: 'Berlin',
      postalCode: '10115',
    },
  },
  FR: {
    country: 'FR',
    name: 'France',
    currency: 'EUR',
    currencySymbol: '€',
    locale: 'fr-FR',
    timezone: 'Europe/Paris',
    phoneCountryCode: '+33',
    taxLabel: 'TVA',
    taxRate: 0.10,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Paris',
      region: 'Île-de-France',
      postalCode: '75001',
    },
  },
  IT: {
    country: 'IT',
    name: 'Italy',
    currency: 'EUR',
    currencySymbol: '€',
    locale: 'it-IT',
    timezone: 'Europe/Rome',
    phoneCountryCode: '+39',
    taxLabel: 'IVA',
    taxRate: 0.10,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Roma',
      region: 'Lazio',
      postalCode: '00100',
    },
  },
  ES: {
    country: 'ES',
    name: 'Spain',
    currency: 'EUR',
    currencySymbol: '€',
    locale: 'es-ES',
    timezone: 'Europe/Madrid',
    phoneCountryCode: '+34',
    taxLabel: 'IVA',
    taxRate: 0.10,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Madrid',
      region: 'Comunidad de Madrid',
      postalCode: '28001',
    },
  },
  NL: {
    country: 'NL',
    name: 'Netherlands',
    currency: 'EUR',
    currencySymbol: '€',
    locale: 'nl-NL',
    timezone: 'Europe/Amsterdam',
    phoneCountryCode: '+31',
    taxLabel: 'BTW',
    taxRate: 0.09,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'phone',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Amsterdam',
      region: 'Noord-Holland',
      postalCode: '1011 AB',
    },
  },
  TR: {
    country: 'TR',
    name: 'Turkey',
    currency: 'TRY',
    currencySymbol: '₺',
    locale: 'tr-TR',
    timezone: 'Europe/Istanbul',
    phoneCountryCode: '+90',
    taxLabel: 'KDV',
    taxRate: 0.08,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Istanbul',
      region: 'Istanbul',
      postalCode: '34000',
    },
  },

  // ─── Middle East & Africa ──────────────────────────
  AE: {
    country: 'AE',
    name: 'United Arab Emirates',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    timezone: 'Asia/Dubai',
    phoneCountryCode: '+971',
    taxLabel: 'VAT',
    taxRate: 0.05,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Dubai',
      region: 'Dubai',
      postalCode: '00000',
    },
  },
  SA: {
    country: 'SA',
    name: 'Saudi Arabia',
    currency: 'SAR',
    currencySymbol: 'SAR',
    locale: 'ar-SA',
    timezone: 'Asia/Riyadh',
    phoneCountryCode: '+966',
    taxLabel: 'VAT',
    taxRate: 0.15,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Riyadh',
      region: 'Riyadh',
      postalCode: '11564',
    },
  },
  QA: {
    country: 'QA',
    name: 'Qatar',
    currency: 'QAR',
    currencySymbol: 'QAR',
    locale: 'ar-QA',
    timezone: 'Asia/Qatar',
    phoneCountryCode: '+974',
    taxLabel: 'No Tax',
    taxRate: 0.00,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Doha',
      region: 'Doha',
      postalCode: '00000',
    },
  },
  ZA: {
    country: 'ZA',
    name: 'South Africa',
    currency: 'ZAR',
    currencySymbol: 'R',
    locale: 'en-ZA',
    timezone: 'Africa/Johannesburg',
    phoneCountryCode: '+27',
    taxLabel: 'VAT',
    taxRate: 0.15,
    taxMode: 'inclusive',
    dietarySystem: 'international',
    primaryContactMethod: 'whatsapp',
    paymentProvider: 'stripe',
    paymentMode: 'disabled',
    addressSample: {
      city: 'Cape Town',
      region: 'Western Cape',
      postalCode: '8001',
    },
  },
};

/**
 * Country names grouped by region — for the Settings UI country picker
 */
export const PRESET_REGIONS: Record<string, string[]> = {
  'Asia-Pacific': ['IN', 'AU', 'NZ', 'SG', 'JP', 'TH'],
  'North America': ['US', 'CA', 'MX'],
  'Europe': ['GB', 'DE', 'FR', 'IT', 'ES', 'NL', 'TR'],
  'Middle East & Africa': ['AE', 'SA', 'QA', 'ZA'],
};

/**
 * Default configuration for The Café Barrackpore (India 🇮🇳)
 * When sold to a foreign client, the admin reconfigures via Settings → Country Preset
 */
export const DEFAULT_RESTAURANT_CONFIG: RestaurantLocalizationConfig = {
  country: 'IN',
  businessName: 'The Café Barrackpore',
  shortName: 'Barrackpore',
  currency: 'INR',
  currencySymbol: '₹',
  locale: 'en-IN',
  timezone: 'Asia/Kolkata',
  phoneCountryCode: '+91',
  phoneValidationMode: 'country',
  openingTime: '11:00 AM',
  closingTime: '11:00 PM',
  isOrderingEnabled: true,
  isTableBookingEnabled: true,
  announcementBanner: null,

  tax: {
    enabled: true,
    mode: 'inclusive',
    label: 'GST',
    rate: 0.05,
  },

  dietary: {
    system: 'india',
  },

  contact: {
    primaryMethod: 'whatsapp',
    phone: '+918420507105',
    displayPhone: '084205 07105',
    whatsapp: '+918420507105',
    email: 'contact@thecafe.com',
  },

  address: {
    line1: '14, Riverside Road, Cantonment',
    city: 'Barrackpore',
    region: 'West Bengal',
    postalCode: '700120',
    country: 'India',
  },

  payments: {
    enabled: false,
    provider: 'razorpay',
    mode: 'disabled',
  },
};
