/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#552100",
        "error-container": "#93000a",
        "on-surface": "#e1e2eb",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary-container": "#582200",
        "surface-tint": "#ffb690",
        "outline-variant": "#584237",
        "surface-container-low": "#191c22",
        "surface-container-lowest": "#0b0e14",
        "primary-fixed-dim": "#ffb690",
        "on-primary-fixed": "#341100",
        "on-surface-variant": "#e0c0b1",
        "surface-dim": "#10131a",
        "secondary-fixed-dim": "#b4c5ff",
        "on-background": "#e1e2eb",
        "primary-fixed": "#ffdbca",
        "inverse-on-surface": "#2e3037",
        "background": "#10131a",
        "inverse-primary": "#9d4300",
        "surface-container-high": "#272a31",
        "primary": "#ffb690",
        "on-secondary": "#002a78",
        "surface-bright": "#363940",
        "surface": "#10131a",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "outline": "#a78b7d",
        "surface-variant": "#32353c",
        "on-tertiary-fixed": "#2a1700",
        "secondary-container": "#0053db",
        "tertiary": "#ffb95f",
        "surface-container": "#1d2026",
        "on-tertiary": "#472a00",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-container-highest": "#32353c",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed": "#00174b",
        "on-error-container": "#ffdad6",
        "secondary": "#b4c5ff",
        "primary-container": "#f97316",
        "secondary-fixed": "#dbe1ff",
        "inverse-surface": "#e1e2eb",
        "on-secondary-container": "#cdd7ff",
        "on-tertiary-container": "#492c00",
        "tertiary-container": "#d78900",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#783200"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        margin: "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Outfit"],
        "label-lg": ["Outfit"],
        "body-sm": ["Inter"],
        "headline-lg": ["Outfit"],
        "display-lg-mobile": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
        "label-md": ["Outfit"],
        "display-lg": ["Outfit"],
        "headline-md": ["Outfit"],
        "headline-sm": ["Outfit"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
