/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#231914",
        "error-container": "#93000a",
        "on-surface": "#E3DACD",
        "tertiary-fixed-dim": "#C39F2B",
        "on-primary-container": "#231914",
        "surface-tint": "#D4AF37",
        "outline-variant": "#4A3B32",
        "surface-container-low": "#1A120E",
        "surface-container-lowest": "#110C09",
        "primary-fixed-dim": "#C39F2B",
        "on-primary-fixed": "#231914",
        "on-surface-variant": "#D1C7BB",
        "surface-dim": "#1C1410",
        "secondary-fixed-dim": "#b4c5ff",
        "on-background": "#E3DACD",
        "primary-fixed": "#F5D058",
        "inverse-on-surface": "#231914",
        "background": "#231914",
        "inverse-primary": "#9d4300",
        "surface-container-high": "#2E211A",
        "primary": "#D4AF37",
        "on-secondary": "#002a78",
        "surface-bright": "#3A2B23",
        "surface": "#231914",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "outline": "#6B5A4E",
        "surface-variant": "#32261F",
        "on-tertiary-fixed": "#231914",
        "secondary-container": "#0053db",
        "tertiary": "#D4AF37",
        "surface-container": "#231914",
        "on-tertiary": "#231914",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-container-highest": "#382921",
        "tertiary-fixed": "#F5D058",
        "on-secondary-fixed": "#00174b",
        "on-error-container": "#ffdad6",
        "secondary": "#b4c5ff",
        "primary-container": "#D4AF37",
        "secondary-fixed": "#dbe1ff",
        "inverse-surface": "#E3DACD",
        "on-secondary-container": "#cdd7ff",
        "on-tertiary-container": "#231914",
        "tertiary-container": "#D4AF37",
        "on-tertiary-fixed-variant": "#231914",
        "on-primary-fixed-variant": "#231914"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        margin: "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
